# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maxime Orione - Portfolio
author: Maxime Orione
email: maxpower98@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hallo, ik ben Maxime Orione - noem me maar Max - en dit is mijn I-Talent Portfolio!
  Ik ben student Application Development op de Hogeschool PXL te Hasselt. Mijn programmeurshart ligt vooral bij webdevelopment, zowel front- als back-end, maar ik hou me ook veel bezig met tekenen.
  Dit portfolio beschrijft de verschillende activiteiten waaraan ik heb meegedaan doorheen mijn opleiding op de hogeschool PXL.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: max-orione
github_username:  Maxzilla60

# Collections
collections:
  activities:
    output: true

# Build settings
markdown: kramdown

# Sass partials directory (for @imports)
sass:
  style: :compressed # Default :expanded

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
